import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { stringify } from "yaml";
import { effectiveContract, generateSuiteSql, loadSuite, parseSuite, runSuite } from "../src/core/suite";
import { combineSuite, fileSuiteIO, splitSuite } from "../src/node/suite-files";
import { validateCsv } from "../src/core/contract";
import type { CsvContract } from "../src/core/model";
import { assertCompleteSqlSummaries } from "../src/core/sql-server-results";
import { spawnSync } from "node:child_process";
import { resolveBaseline, resolveTargetBaseline, baselineReferences } from "../src/core/baseline";

test("target baseline dependencies retain relative meaning through combine and split", async (t) => {
  const { root, master } = await fixture(t);
  const baseline = { baselineVersion: 1, revision: 1, capturedAt: "2026-09-11T00:00:00Z", sourceKind: "sql", captureMethod: "sql-metadata", columns: [{ name: "Id", ordinal: 1, collation: "Latin1_General_100_BIN2", uniqueKeys: '[{"name":"PK_Test","ordinal":1}]' }] };
  await writeFile(join(root, "schema.yaml"), stringify(baseline));
  const c = contract(); c.sqlServer = { targets: [{ connection: "test", schema: "dbo", table: "A", baseline: { ref: "../schema.yaml" } }] };
  await writeFile(join(root, "contracts", "a.yaml"), stringify(c));
  const bundle = join(root, "portable.yaml");
  await combineSuite(master, bundle, { allowExternal: true });
  const portable = await loadSuite(bundle, fileSuiteIO);
  assert.deepEqual(baselineReferences(portable.members[0].contract!), ["schema.yaml"]);
  const resolved = await resolveBaseline(portable.members[0].contract!, bundle, fileSuiteIO);
  assert.deepEqual(resolved.sqlServer?.targets?.[0].baseline, baseline);
  const executionTarget = await resolveTargetBaseline(portable.members[0].contract!.sqlServer!.targets![0], bundle, fileSuiteIO);
  assert.deepEqual(executionTarget.baseline, baseline);
  const split = await splitSuite(bundle, join(root, "split"));
  const reloaded = await loadSuite(split.master, fileSuiteIO);
  const again = await resolveBaseline(reloaded.members[0].contract!, reloaded.members[0].source, fileSuiteIO);
  assert.deepEqual(again.sqlServer?.targets?.[0].baseline, baseline);
});

const contract = (table = "Employees"): CsvContract => ({ version: 1, schema: { columns: { Id: { presence: "required", constraints: { allowedValues: ["001", "NULL", "true"] } } } }, sqlServer: { connection: "test", schema: "dbo", table } });
async function fixture(t: { after(fn: () => Promise<void>): void }) {
  const root = await mkdtemp(join(tmpdir(), "contract-suite-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(join(root, "contracts"));
  await writeFile(join(root, "contracts", "a.yaml"), "# Contract comment\n" + stringify(contract()));
  await writeFile(join(root, "contracts", "b.yaml"), stringify({ ...contract("Departments"), schema: { columns: { Department: { presence: "required" } } } }));
  const master = join(root, "master.csvsuite.yaml");
  await writeFile(master, stringify({ suiteVersion: 1, id: "hcm", metadata: { revision: "001" }, members: [{ id: "employees", ref: "./contracts/a.yaml" }, { id: "departments", ref: "./contracts/b.yaml" }] }));
  return { root, master };
}
test("combine/split preserves heterogeneous contracts, metadata, literals, order, comments and generated checks", async (t) => {
  const { root, master } = await fixture(t);
  const bundle = join(root, "portable.csvsuite.yaml");
  assert.equal((await combineSuite(master, bundle)).portable, true);
  const referenced = await loadSuite(master, fileSuiteIO);
  const portable = await loadSuite(bundle, fileSuiteIO);
  assert.deepEqual(portable.members.map((m) => m.contract), referenced.members.map((m) => m.contract));
  assert.deepEqual(generateSuiteSql(portable), generateSuiteSql(referenced));
  assert.match(await readFile(bundle, "utf8"), /Contract comment/);
  const split = await splitSuite(bundle, join(root, "split"));
  const restored = await loadSuite(split.master, fileSuiteIO);
  assert.deepEqual(restored.members.map((m) => m.contract), referenced.members.map((m) => m.contract));
  assert.equal(parseSuite(await readFile(split.master, "utf8")).metadata?.revision, "001");
  await assert.rejects(combineSuite(master, bundle), /overwrite/);
  await assert.rejects(splitSuite(bundle, join(root, "split")), /overwrite/);
  await combineSuite(master, bundle, { force: true });
  const sql = generateSuiteSql(portable);
  assert.equal(sql.batches.length, 2);
  assert.equal(sql.sql.match(/^GO$/gm)?.length, 2);
  assert.doesNotMatch(sql.sql, /t\.\*/);
});
test("connection defaults are atomic and target overrides contract overrides suite", () => {
  const c = contract();
  c.sqlServer = { schema: "dbo", table: "A" };
  assert.equal(effectiveContract(c, { connection: "shared" }).sqlServer?.connection, "shared");
  c.sqlServer = { connection: "member", targets: [{ schema: "dbo", table: "A" }, { schema: "dbo", table: "B", integratedConnection: { server: "local", database: "test" } }] };
  const result = effectiveContract(c, { connection: "shared" });
  assert.equal(result.sqlServer?.targets?.[0].connection, "member");
  assert.equal(result.sqlServer?.targets?.[1].connection, undefined);
  assert.equal(result.sqlServer?.targets?.[1].integratedConnection?.database, "test");
  assert.equal(c.sqlServer.targets?.[0].connection, undefined);
});
test("invalid references and cycles stay visible; duplicate IDs fail before execution", async (t) => {
  const { root, master } = await fixture(t);
  await writeFile(join(root, "contracts", "a.yaml"), stringify({ suiteVersion: 1, id: "cycle", members: [{ id: "back", ref: "../master.csvsuite.yaml" }] }));
  const suite = await loadSuite(master, fileSuiteIO);
  assert.match(suite.members[0].error!, /Reference cycle/);
  await rm(join(root, "contracts", "a.yaml"));
  assert.match((await loadSuite(master, fileSuiteIO)).members[0].error!, /ENOENT/);
  assert.throws(() => parseSuite("suiteVersion: 1\nid: x\nmembers:\n- {id: a, ref: x}\n- {id: a, ref: y}"), /duplicate/);
  assert.throws(() => parseSuite("suiteVersion: 1\nid: x\nmembers: []"), /at least one/);
  await assert.rejects(combineSuite(master, join(root, "bad.yaml")), /ENOENT/);
});
test("collect-all and fail-fast distinguish assertion failure, execution error, skipped and no-target", async (t) => {
  const { master } = await fixture(t);
  const suite = await loadSuite(master, fileSuiteIO);
  const assertion = await runSuite(suite, async (c) => validateCsv(c, "Id\ninvalid\n"));
  assert.equal(assertion.exitCode, 1);
  assert.equal(assertion.valid, false);
  let calls = 0;
  const runner = async (c: CsvContract) => { if (++calls === 1) throw new Error("synthetic execution error"); return validateCsv(c, "Department\nIT\n"); };
  const all = await runSuite(suite, runner);
  assert.deepEqual(all.runs.map((r) => r.status), ["ERROR", "PASS"]);
  assert.equal(all.exitCode, 2);
  calls = 0;
  const fast = await runSuite(suite, runner, true);
  assert.deepEqual(fast.runs.map((r) => r.status), ["ERROR", "SKIPPED"]);
  assert.equal(calls, 1);
  delete suite.members[0].contract!.sqlServer;
  const missing = await runSuite(suite, runner);
  assert.equal(missing.runs[0].status, "ERROR");
});
test("external paths retain meaning after relocation and are reported as nonportable", async (t) => {
  const { root, master } = await fixture(t);
  const c = contract(); c.targets = [{ path: "../data/people.csv" }];
  await writeFile(join(root, "contracts", "a.yaml"), stringify(c));
  await mkdir(join(root, "moved"));
  const output = join(root, "moved", "bundle.yaml");
  await assert.rejects(combineSuite(master, output), /not portable/);
  const result = await combineSuite(master, output, { allowExternal: true });
  assert.equal(result.portable, false);
  const inline = parseSuite(await readFile(output, "utf8"));
  assert.equal(resolve(root, "moved", inline.members[0].contract!.targets![0].path!), resolve(root, "data/people.csv"));
  const split = await splitSuite(output, join(root, "elsewhere"));
  const restored = await loadSuite(split.master, fileSuiteIO);
  assert.equal(resolve(root, "elsewhere", restored.members[0].contract!.targets![0].path!), resolve(root, "data/people.csv"));
});
test("unsupported fields, ambiguous YAML and secret-bearing connections are rejected", async (t) => {
  const { root, master } = await fixture(t);
  const output = join(root, "out.yaml");
  await writeFile(join(root, "contracts", "a.yaml"), stringify({ ...contract(), unknownRule: true }));
  await assert.rejects(combineSuite(master, output), /invalid contract|Invalid contract/);
  await writeFile(join(root, "contracts", "a.yaml"), stringify(contract()).replace("connection: test", "connection: 'Server=local;Password=secret'"));
  await assert.rejects(combineSuite(master, output), /profile name/);
  await writeFile(join(root, "contracts", "a.yaml"), "version: 1\nversion: 1\nschema: {columns: {}}\n");
  await assert.rejects(combineSuite(master, output), /unique/);
});
test("single contracts remain loadable and run with the same validator", async (t) => {
  const { root } = await fixture(t);
  const single = await loadSuite(join(root, "contracts", "a.yaml"), fileSuiteIO);
  assert.equal(single.isSuite, false);
  assert.equal((await runSuite(single, async (c) => validateCsv(c, "Id\n001\n"))).valid, true);
});
test("SQL responses cannot silently omit or corrupt expected rules", () => {
  assert.throws(() => assertCompleteSqlSummaries(["a"], []), /expected rule/);
  assert.throws(() => assertCompleteSqlSummaries(["a"], [{ RuleId: "a", FailureCount: "NaN" }]), /Invalid/);
  assert.throws(() => assertCompleteSqlSummaries(["a"], [{ RuleId: "a", FailureCount: 0 }, { RuleId: "a", FailureCount: 0 }]), /unexpected/);
  assert.doesNotThrow(() => assertCompleteSqlSummaries(["a"], [{ RuleId: "a", FailureCount: "0" }]));
});
test("CLI returns execution-error JSON without connecting and CSV suites retain inline member identity", async (t) => {
  const { root, master } = await fixture(t);
  await rm(join(root, "contracts", "a.yaml"));
  await rm(join(root, "contracts", "b.yaml"));
  const cli = resolve("dist/cli/csv-contract.cjs");
  const bad = spawnSync(process.execPath, [cli, "dbtest", "--spec", master, "--format", "json"], { encoding: "utf8" });
  assert.equal(bad.status, 2, bad.stderr);
  const report = JSON.parse(bad.stdout);
  assert.equal(report.valid, false);
  assert.deepEqual(report.runs.map((r: { status: string }) => r.status), ["ERROR", "ERROR"]);
  const c = contract(); delete c.sqlServer; c.targets = [{ path: "./input.csv" }];
  await writeFile(join(root, "input.csv"), "Id\n001\n");
  await writeFile(master, stringify({ suiteVersion: 1, id: "files", members: [{ id: "one", contract: c }, { id: "two", contract: c }] }));
  const csv = spawnSync(process.execPath, [cli, "test", "--spec", master, "--format", "json"], { encoding: "utf8" });
  assert.equal(csv.status, 0, csv.stderr);
  const result = JSON.parse(csv.stdout);
  assert.equal(result.runs.length, 2);
  assert.equal(result.performance.passes, 1);
  assert.notEqual(result.runs[0].spec, result.runs[1].spec);
});
test("unsafe integer literals and aliases are never silently changed by conversion", async (t) => {
  assert.throws(() => parseSuite("suiteVersion: 1\nid: s\nmetadata: {number: 9007199254740993}\nmembers: [{id: a, ref: a}]"), /losslessly/);
  const { root, master } = await fixture(t);
  await writeFile(join(root, "contracts", "a.yaml"), "version: 1\nschema:\n  columns:\n    A: &column {presence: required}\n    B: *column\nsqlServer: {connection: test, schema: dbo, table: T}\n");
  await assert.rejects(combineSuite(master, join(root, "alias.yaml")), /anchors or aliases/);
});
